name: Build RealisticWorldGenerator api
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: Building maven project
        run: mvn -B package --file legacy-api/pom.xml
      - name: Publish to GitHub Packages
        run: mvn deploy --file legacy-api/pom.xml -s ${{ github.workspace }}/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}
